name: taxi_weather
version: '1.0.0'
profile: taxi_weather

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Define variables that allow referencing the raw dataset from dbt models
vars:
  raw_dataset: "taxi_raw"
  PAYMENT_TYPE_POLICY_TAG: "projects/proyectomanu/locations/europe-west1/taxonomies/918566496354584264/policyTags/8265901397227505812"


models:
  taxi_weather:
    staging:
      materialized: incremental
      incremental_strategy: merge
    mart:
      materialized: table
      +schema: "{{ env_var('MART_DATASET_NAME', 'taxi_mart') }}"